### PR TITLE
Events session storage

### PR DESCRIPTION
**Pull request by bramosja**
# Description
Added style on the events that belong to a user's friends, and remove expired events from the DOM so that the most recent event remains at the top.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Testing Instructions for Change Made
1. `git fetch --all`
1. `git checkout britt-tackles-session-storage`
1. Run grunt
1. Copy and paste the database below to your database.json
1. Sign in to the session with the user name "Bart Turtle" and the email address "bartTurtle@duckNcover.com"
1. Make sure that you can only see events that belong to Bart Turtle and Betty Turtle
1. Click on the "Events" page
1. Check that the article by Betty Turtle is Italicized and the color cornsilk
1. Add an event and in the "date" field, add a past date
1. When clicking "save event" make sure that event does NOT save to DOM

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added test instructions that prove my fix is effective or that my feature works

```
{
  "users": [
    {
      "id": 1,
      "name": "userName",
      "email": "userEmail@gmail.com"
    },
    {
      "id": 2,
      "name": "userName2",
      "email": "userEmail2@gmail.com"
    },
    {
      "name": "userName3",
      "email": "userEmail3@gmail.com",
      "id": 3
    },
    {
      "name": "Betty Turtle",
      "email": "bettyTurtle@duckNcover.com",
      "id": 4
    },
    {
      "name": "Bart Turtle",
      "email": "bartTurtle@duckNcover.com",
      "id": 5
    },
    {
      "name": "Teddy Turtle",
      "email": "teddyTurtle@duckNcover.com",
      "id": 6
    }
  ],
  "events": [
    {
      "name": "Meet Betty Turtle",
      "date": "2019-01-22T12:30",
      "location": "Single Turtles Society HQ",
      "userId": 5,
      "id": 1
    },
    {
      "name": "Learn the Foxtrot",
      "date": "2019-01-16T17:00",
      "location": "Turtles Only Open Dance Floor",
      "userId": 5,
      "id": 2
    },
    {
      "name": "Help orphan turtles find homes",
      "date": "2019-01-15T11:00",
      "location": "Tiny Turtle Orphanage",
      "userId": 4,
      "id": 3
    },
    {
      "name": "Destroy orphan turtles homes",
      "date": "2019-01-15T11:00",
      "location": "Tiny Turtle Orphanage",
      "userId": 1,
      "id": 3
    },
    {
      "name": "Name",
      "date": "2019-12-16T18:00",
      "location": "Location",
      "userId": 5,
      "id": 4
    },
    {
      "name": "Yesterday Event",
      "date": "2019-01-12T08:00",
      "location": "Nowhere",
      "userId": 5,
      "id": 5
    }
  ],
  "articles": [
    {
      "id": 1,
      "title": "User 1 Article (fourth)",
      "url": "http://google.com",
      "synopsis": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus efficitur purus eget est rutrum tincidunt. Vestibulum a velit accumsan quam scelerisque efficitur. Proin tincidunt magna id orci ultricies vulputate. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis laoreet lacus nibh, id tincidunt enim euismod in. Sed egestas sapien orci, in vestibulum ipsum tempor id. Aenean eleifend mi dui, in consequat lacus laoreet quis.",
      "timestamp": "1457395221082",
      "userId": 1
    },
    {
      "id": 2,
      "title": "User 2 Article (second)",
      "url": "http://google.com",
      "synopsis": "Fusce turpis mi, sollicitudin quis maximus ac, facilisis vel lectus. Duis laoreet sollicitudin odio at viverra. Phasellus scelerisque, ante id lacinia cursus, elit nunc ullamcorper ipsum, vel faucibus sapien lectus nec nisl. In dui lorem, dignissim sit amet turpis pulvinar, congue malesuada ligula. Morbi dignissim, est vel lacinia mollis, magna ligula posuere arcu, rhoncus ultricies est dui vel risus.",
      "timestamp": "1247395221082",
      "userId": 2
    },
    {
      "id": 3,
      "title": "User 2 Article2 (third)",
      "url": "http://google.com",
      "synopsis": "Fusce turpis mi, sollicitudin quis maximus ac, facilisis vel lectus. Duis laoreet sollicitudin odio at viverra. Phasellus scelerisque, ante id lacinia cursus, elit nunc ullamcorper ipsum, vel faucibus sapien lectus nec nisl. In dui lorem, dignissim sit amet turpis pulvinar, congue malesuada ligula. Morbi dignissim, est vel lacinia mollis, magna ligula posuere arcu, rhoncus ultricies est dui vel risus.",
      "timestamp": "1447395221082",
      "userId": 2
    },
    {
      "id": 4,
      "title": "User 3 Article (first)",
      "url": "http://google.com",
      "synopsis": "Fusce turpis mi, sollicitudin quis maximus ac, facilisis vel lectus. Duis laoreet sollicitudin odio at viverra. Phasellus scelerisque, ante id lacinia cursus, elit nunc ullamcorper ipsum, vel faucibus sapien lectus nec nisl. In dui lorem, dignissim sit amet turpis pulvinar, congue malesuada ligula. Morbi dignissim, est vel lacinia mollis, magna ligula posuere arcu, rhoncus ultricies est dui vel risus.",
      "timestamp": "1047395221082",
      "userId": 3
    },
    {
      "id": 5,
      "title": "User 4 Article",
      "url": "http://google.com",
      "synopsis": "Fusce turpis mi, sollicitudin quis maximus ac, facilisis vel lectus. Duis laoreet sollicitudin odio at viverra. Phasellus scelerisque, ante id lacinia cursus, elit nunc ullamcorper ipsum, vel faucibus sapien lectus nec nisl. In dui lorem, dignissim sit amet turpis pulvinar, congue malesuada ligula. Morbi dignissim, est vel lacinia mollis, magna ligula posuere arcu, rhoncus ultricies est dui vel risus.",
      "timestamp": "1647495221082",
      "userId": 4
    },
    {
      "title": "timestamp test (fifth)",
      "synopsis": "time!",
      "url": "meg.com",
      "timestamp": 1547395221082,
      "date": "01/13/2019 at 10:0",
      "userId": 2,
      "id": 6
    },
    {
      "title": "another timestamp (sixth)",
      "synopsis": "time time time",
      "url": "meg.com",
      "timestamp": 1547395320738,
      "date": "01/13/2019 at 10:2",
      "userId": 2,
      "id": 7
    },
    {
      "title": "it's a new hour",
      "synopsis": "woo!",
      "url": "meg.com",
      "timestamp": 1547402892179,
      "date": "01/13/2019 at 12:08",
      "userId": 2,
      "id": 10
    },
    {
      "title": "user2 @ 11:46",
      "synopsis": "Fusce turpis mi, sollicitudin quis maximus ac, facilisis vel lectus. Duis laoreet sollicitudin odio at viverra. Phasellus scelerisque, ante id lacinia cursus, elit nunc ullamcorper ipsum, vel faucibus sapien lectus nec nisl. In dui lorem, dignissim sit amet turpis pulvinar, congue malesuada ligula. Morbi dignissim, est vel lacinia mollis, magna ligula posuere arcu, rhoncus ultricies est dui vel risus.",
      "url": "meg.com",
      "timestamp": 1547488036316,
      "date": "1/14/2019 at 11:47AM",
      "userId": 2,
      "id": 11
    },
    {
      "title": "user1 @ 11:47",
      "synopsis": "Fusce turpis mi, sollicitudin quis maximus ac, facilisis vel lectus. Duis laoreet sollicitudin odio at viverra. Phasellus scelerisque, ante id lacinia cursus, elit nunc ullamcorper ipsum, vel faucibus sapien lectus nec nisl. In dui lorem, dignissim sit amet turpis pulvinar, congue malesuada ligula. Morbi dignissim, est vel lacinia mollis, magna ligula posuere arcu, rhoncus ultricies est dui vel risus.",
      "url": "meg.com",
      "timestamp": 1547488061390,
      "date": "1/14/2019 at 11:47AM",
      "userId": 1,
      "id": 12
    }
  ],
  "tasks": [],
  "messages": [
    {
      "id": 1,
      "message": "messageContent",
      "time": "messageTime",
      "userId": 1
    }
  ],
  "connections": [
    {
      "id": 1,
      "userId": 1,
      "otherId": 2
    },
    {
      "id": 2,
      "userId": 1,
      "otherId": 3
    },
    {
      "id": 3,
      "userId": 2,
      "otherId": 1
    },
    {
      "id": 4,
      "userId": 5,
      "otherId": 4
    },
    {
      "id": 5,
      "userId": 5,
      "otherId": 6
    }
  ]
}
```

### CODE REVIEW

**Review by megcruzen — APPROVED** [review]
🐢 🐢 🐢

**Comment by megcruzen** [comment]
If I log in as `userName` (email: `userEmail@gmail.com`) and add a new event, my event is saved to the database but it's not showing on the DOM. 😢 I should be able to see my own events, right?

**Comment by megcruzen** [comment]
I got confused for a minute and was wondering why my event wasn't getting added - because your code works! 😅 As a stretch goal, having a message that says "Please select a future date" would be cool.

**Review by huntermetts — APPROVED** [review]
Hizzar!

**Pull request merged**
